### PR TITLE
Remove unused strings

### PR DESCRIPTION
**Pull request by TheoChevalier**
Waiting on https://github.com/MozillaFoundation/Advocacy/issues/612 to see if I can remove more content

### CODE REVIEW

**Comment by ScottDowne** [comment]
@TheoChevalier Is this something you want me to look at now, or waiting on MozillaFoundation/Advocacy#612 still?

**Comment by TheoChevalier** [comment]
I think we can just merge that, then I will create a new PR with the current en-US email template, or the updated one.

**Comment by ScottDowne** [comment]
@TheoChevalier whoops, looks like additional_info and additional_info_thunderbird are currently used.

**Comment by ScottDowne** [comment]
@TheoChevalier I reverted it, hopefully in time before pontoon saw it.

I think if you remake the pull request, but add back `additional_info` and `additional_info_thunderbird` we can try again?

**Comment by TheoChevalier** [comment]
Thanks for catching that! I just blindly assumed those strings were only used for tiles directory… 
Yeah, looks like you reverted it on time *hats off*

**Comment by ScottDowne** [comment]
Yeah, I assumed that too. Hilariously, I was probably the one to use that string in the first place...

**Pull request merged**
