### PR TITLE
Fix issue #311 - Intl is undefined for Safari

### LINKED ISSUE #311: Our page doesn't work on Safari
```
[Error] ReferenceError: Can't find variable: Intl
```

### PR DESCRIPTION
**Pull request by alicoding**
Adding polyfill for Safari for Intl and navigator.languages

Closes #311

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne and @jbuck R?

**Comment by jbuck** [comment]
I don't think we should land this patch as-is.

https://github.com/andyearnshaw/Intl.js/#intljs-and-browserifywebpack indicates that we'll need to load the locale data as well. We should be loading the correct locale data too. And the accept-language polyfill is 100% not ready for production use

**Comment by ScottDowne** [comment]
Status on this?

**Comment by alicoding** [comment]
I need to update webpack to also include other language pack.

**Comment by alicoding** [comment]
@jbuck R?

**Comment by alicoding** [comment]
r+ from the call will file an issue if we want to optimize.

**Pull request merged**
