### PR TITLE
Fixing locale pick for es-MX

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@TheoChevalier thoughts?

**Comment by ScottDowne** [comment]
This is the es messages used in es-MX, and in general, I'm adding a function that we can scale up if we find more cases like this.

**Comment by TheoChevalier** [comment]
I tested the PR on a local instance, and it works as I would expect it to work with different locale codes as accepted-language (mainly tried with es, es-MX, es-CL, and mixing them), so looks good to me 👍

**Comment by ScottDowne** [comment]
@TheoChevalier great. I'll push it up to prod tomorrow morning.

**Pull request merged**
