### PR TITLE
Add logo and update copy on Stripe Checkout

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
@ScottDowne r?

**Comment by ScottDowne** [comment]
R+

**Comment by jbuck** [comment]
@ScottDowne will this conflict with your reduced address info patch?

**Comment by ScottDowne** [comment]
Nope, shouldn't conflict. I'll double check.

**Comment by ScottDowne** [comment]
https://donate.mofostaging.net/en-US/
https://donate.mofostaging.net/en-US/?billingAddress=partial

All clear.

**Pull request merged**
