### PR TITLE
Add A/B testing for our about sidebar text in EN locales

### PR DESCRIPTION
**Pull request by Pomax**
This adds a new string to the messages.properties for `en-US` only, as per https://github.com/mozilla/donate.mozilla.org/issues/2129, and adds an A/B test that does a 50/50 content swap between the original text and the new text.

### CODE REVIEW

**Comment by alanmoo** [comment]
I would assume so too. @WillatMozFdn can you confirm?

**Comment by WillatMozFdn** [comment]
Yes, that would be ideal if we can.  Thanks @TheoChevalier

**Comment by TheoChevalier** [comment]
Sounds good, let’s merge this sooner rather than later then :)

**Comment by Pomax** [comment]
We can even land it immediately if we want, with the original text set to 100%, if we don't want to start testing the new text until the 21st. The code knows how to handle more than one active test at a time.

**Comment by Pomax** [comment]
I have no idea what Travis is doing. Somehow webpack's failing even though it shouldn't because it's supposedly using webpack 3.2.0, which is the correct version.

**Comment by alanmoo** [comment]
In addition to the webpack stuff, it seems like there's a handful of linting issues with the new file.

**Comment by Pomax** [comment]
assuredinfantilejaguar-small

**Pull request closed without merging**
