### PR TITLE
Setup logic for handling micro payment switching

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@cadecairos ping! :rocket: 

If you don't think you can find the time today, let me know, so I can make other plans. It's not mandatory that you do this, but if you cannot, I need to know.

**Comment by ScottDowne** [comment]
@cadecairos ping pong :ping_pong:

**Comment by ScottDowne** [comment]
@cadecairos I rebased this, so we can now use this as part 2 of the patch.

**Comment by cadecairos** [comment]
Besides my only comment above, this looks solid and works as expected. R+ once the comment above is addressed.

**Comment by ScottDowne** [comment]
@cadecairos updated, mind taking another look?

**Comment by ScottDowne** [comment]
@cadecairos can wait until tomorrow.

**Pull request merged**
