### PR TITLE
Fix Russian translation glitch "Проверить"/"Чек"

### PR DESCRIPTION
**Pull request by ValdikSS**
"Проверить" is to check something, "Чек" is payment by check.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
@BychekRU @unghost r?

**Comment by ValdikSS** [comment]
https://donate.mozilla.org/ru/
`Другие способы пожертвования: Биткойн | Проверить`

**Comment by BychekRU** [comment]
r+

**Comment by TheoChevalier** [comment]
Thanks @bychekRU, and thanks @ValdikSS for fixing it :)

**Pull request merged**
