### PR TITLE
Fix issue #93 - Add mofo style jslint

### LINKED ISSUE #93: Add MoFo JavaScript Style Guide to the repo
@ScottDowne @alicoding ?

Should we be using this:
https://github.com/MozillaFoundation/javascript-style-guide

### PR DESCRIPTION
**Pull request by alicoding**
closes #93

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

**Comment by alicoding** [comment]
@ScottDowne this is now rebased, so you can review again if you have :P

**Comment by alicoding** [comment]
The test will failed because of the thing we've discussed @ScottDowne

**Comment by ScottDowne** [comment]
I guess this is fine.

Note, this means we now fail travis, because we're testing for things we were not before.

This makes cleaning this up a priority, and I'm not sure how I feel about this.

**Pull request merged**
