### PR TITLE
Another attempt at locale build step, now with less files.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@alicoding better?

**Comment by alicoding** [comment]
Travis is failing

**Comment by ScottDowne** [comment]
Yup it says it cannot create the locales.json file. Dunno why. Thoughts?

**Comment by alicoding** [comment]
You might want to add before_scripts to travis.yml to run build:locale first?

**Comment by alicoding** [comment]
r+

**Pull request merged**
