### PR TITLE
adding privacy checkbox to signup page

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
r?

**Comment by alicoding** [comment]
Is there an issue somewhere for this ?

**Comment by ScottDowne** [comment]
Nope, no issue.

**Comment by alicoding** [comment]
How do I test this? I don't see this was added anywhere when I test with `?test=signup-test`

**Comment by ScottDowne** [comment]
It should be there on all signups, no query required, let me double check.

**Comment by ScottDowne** [comment]
So the regular thank-you should have the checkbox.

I'm making it so the new flow thank-you also has the privacy checkbox.

/thank-you/?test=new-flow-test

**Comment by alicoding** [comment]
Awesome!

**Pull request merged**
