### PR TITLE
Updating some thank you strings.

### PR DESCRIPTION
**Pull request by ScottDowne**
Fixing https://github.com/MozillaFoundation/Advocacy/issues/1016

### CODE REVIEW

**Comment by ScottDowne** [comment]
@TheoChevalier @WillatMozFdn

**Comment by TheoChevalier** [comment]
Aren’t we getting a whole new copy? In this case, it would make more sense to wait for the new copy instead of translating the strings twice. If @WillatMozFdn needs the strings right away, maybe we can just search and replace `2016` with `2017`, then localize the brand new copy?
How does that sound?

**Comment by ScottDowne** [comment]
I thought just removing the "in 2016" bit was all we were doing. If there is new copy, then yes, I agree with you. Let me double check.

**Comment by ScottDowne** [comment]
Double checked, we're good on this change for the next several months.

**Pull request merged**
