### PR TITLE
New styles

### PR DESCRIPTION
**Pull request by ScottDowne**
Fixes: https://github.com/mozilla/donate.mozilla.org/issues/2008

### CODE REVIEW

**Comment by ScottDowne** [comment]
It should do an AB test for the nav.

**Comment by alanmoo** [comment]
@gvn Please work with Scott to dig into the why and how of this. I recognize it'll take a while but it's worth getting this right. (It's not on fire though)

**Comment by ScottDowne** [comment]
@gvn yeah, but I think @kristinashu did that in the issue not the pr.

Also good catch on the footer background.

**Comment by gvn** [comment]
Ok, in that case, code looks good!

**Pull request merged**
