### PR TITLE
Footer and font changes

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@kristinashu review app should be done soon.

This is footer layout changes.

Re assign to a dev for review if it looks good.

**Comment by kristinashu** [comment]
Looks fine but can you please make the mozilla logo link to http://foundation.mozilla.org/

**Comment by ScottDowne** [comment]
@kristinashu is there a ticket for this? Maybe just drop in the redpens.

**Comment by kristinashu** [comment]
There was no ticket or design for this. It was the compromise between having the Foundation site footer layout and donate page content.

**Comment by TheoChevalier** [comment]
Tiny regression in RTL, this block of text should be aligned on the right

image

**Comment by ScottDowne** [comment]
@TheoChevalier updated.

**Comment by TheoChevalier** [comment]
Thanks! Looks good 👍

**Pull request merged**
