### PR TITLE
Disable and hide postal code input if the country doesn't have them

### LINKED ISSUE #925: erm... apparently there are no postal codes in Bolivia?
More of an "FYI" as we have received $0 from Bolivia (but maybe this is part of the reason why?)

i_tried_to_donate__10u_s__-_andrea_mozillafoundation_org_-_mozilla_mail

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #925

### CODE REVIEW

**Comment by cadecairos** [comment]
@ScottDowne / @alicoding I can't figure out how to test this - There doesn't appear to be a way to change react component state in the test utils?

**Comment by cadecairos** [comment]
Oh. "updateState" how nice

**Comment by cadecairos** [comment]
Nope, doesn't work. the component isn't mounted, and can't have set state called

**Comment by jbuck** [comment]
We're switching to the one-page form so we don't need to land this

**Pull request closed without merging**
