### PR TITLE
Allow inserting Optimize.ly images

### PR DESCRIPTION
**Pull request by kyoshino**
At MozLando, we are working on an [Engagement sprint](https://wiki.mozilla.org/Engagement/Mozlando_Projects/Pitch_Presentations) to boost email opt-ins on the Thank You page. I’d like to specify the background image quickly via Optimizely but the CSP doesn’t allows us to do so. Can we make this change? It should not be harmful. Thanks!

### CODE REVIEW

**Comment by kyoshino** [comment]
Sorry to bother you but we'd like to start our A/B tests today.

**Comment by alicoding** [comment]
cc @jbuck @adamlofting

**Comment by adamlofting** [comment]
@kyoshino can you let me know when the test is ready in Optimizely for review please? It will only take me a couple of minutes to check but I'll need to squeeze this in between meetings.

**Comment by adamlofting** [comment]
I'm merging this patch now, but we'll need @jbuck to push this to production.

**Comment by kyoshino** [comment]
@adamlofting Yes, I was wondering who can review our tests. I'll ping you once ready.

**Comment by kyoshino** [comment]
Looks like this change is now on prod. Thanks everyone!

**Pull request merged**
