### PR TITLE
Issue 1059 ID Missing Amount

### LINKED ISSUE #1059: id doesn't display amount in the button
STR:

1. go here: https://donate.mozilla.org/id/
2. click an amount
expected: button should show the amount
actual: button shows new text

This seems to be an issue with the localized text no containing the {amount} variable.

### PR DESCRIPTION
**Pull request by alicoding**
Closes #1059
In the indonesian translation, the donation amount was not being shown on the button. Removed the translation string and also changed the donate_now message as it could not be verified as correct.
(via @renvrant)

### CODE REVIEW

**Comment by ScottDowne** [comment]
R+

**Comment by flodolo** [comment]
@bennychandra @kelimuttu @rodin 
Can you take a look at this? We currently have 2 strings for Indonesian
```
donate_now=Berdonasilah sekarang
donate_now_amount=Sumbang sekarang
```
English is
```
donate_now=Donate now
donate_now_amount=Donate { donationAmount } now
```
Indonesian is missing the variable in the second string. Can you provide the correct translation for these 2 strings? Providing them here would work.

**Comment by bennychandra** [comment]
donate_now=Berdonasi sekarang
donate_now_amount=Berdonasi { donationAmount } sekarang

**Comment by flodolo** [comment]
Thanks Benny :+1:

**Comment by flodolo** [comment]
@alicoding Looks good to merge

**Pull request merged**
