### PR TITLE
25s timeouts for paypal and stripe requests

### PR DESCRIPTION
**Pull request by cadecairos**
#829 

@jbuck R?

### CODE REVIEW

**Comment by ScottDowne** [comment]
@cadecairos or @jbuck when it times out, the user gets a generic error?

**Comment by cadecairos** [comment]
@ScottDowne It should get a https://httpstatuses.com/408 instead of a https://httpstatuses.com/503

**Comment by alicoding** [comment]
Can I test this somehow?

**Comment by ScottDowne** [comment]
@alicoding maybe with no network.

**Comment by cadecairos** [comment]
@alicoding you could use an intercepting proxy like ZAProxy, intercept requests to paypal/stripe and then let the request timeout.

shameless plug: https://chrisdecairos.ca/intercepting-traffic-with-zaproxy/

**Comment by jbuck** [comment]
@cadecairos this looks good, but I'm curious what happens the users hit this error... do they just get a "try again" message?

**Comment by cadecairos** [comment]
No, they get json, because this is a redirect. that's why I keep saying we need a landing page for errors!

**Comment by jbuck** [comment]
As shitty as that is, people currently get a nice 503 page from Heroku....

**Pull request merged**
