### PR TITLE
Remove two sequential tests

### PR DESCRIPTION
**Pull request by alicoding**
Our server API changed in a way that causes the signup on our old form to break and I don't know if it's worth keeping it up to date and working on this old form. I think it is better to just remove this and maintain our current form.

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

**Comment by jbuck** [comment]
@alicoding don't remove the tests without removing the code too :)

I'd leave the decision up to Scott though.

**Comment by ScottDowne** [comment]
Still not in a rush to touch sequential. Running those tests are indirectly
testing components too. Components we do use. Until we have better test
coverage I'm hesitant to remove tests.

**Comment by alicoding** [comment]
@ScottDowne the tests still needs to be removed because it's throwing error `500` from the server causes it to stuck on those sequential page tests. We either have to fix the server to make it work for both old and new form or totally remove them now.

**Pull request closed without merging**
