### PR TITLE
Changed the heart fill color to red

### PR DESCRIPTION
**Pull request by WesleyBranton**
The heart image looks a little boring with the plain white color, so I think it should be changed to red.

### CODE REVIEW

**Comment by alanmoo** [comment]
@kristinashu any thoughts on this?

**Comment by WesleyBranton** [comment]
@kristinashu am I missing something? There is only one heart on the donate.mozilla.org page and the site is quite bland looking. Am I not looking at the correct site?

**Comment by kristinashu** [comment]
Oh sorry @WesleyBranton! I thought this was for a different project. I still think we should keep the heart as is though since we don't want to distract users from the main focus of donating. 

We are currently exploring new designs for this page and plan to try out different treatments so we'll keep this in mind!

**Comment by WesleyBranton** [comment]
@kristinashu is there a link to a discussion about the redesign or anything? I'd love to submit my ideas.

**Comment by WesleyBranton** [comment]
Thanks

**Pull request closed without merging**
