### PR TITLE
Redux prop

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@TheoChevalier or @vojtechmzl I tried to reduce my previous redux patch down into smaller commits by removing changes unrelated to redux.

The only reason I felt the need to do these before redux is to remove the amount of components and tests that needed to be updated to support redux.

I suggest review the commits from first to last, and we'll land any above the first commit that fails.

@cadecairos Adding you now, because I got the commit down smaller.

Thoughts?

**Comment by TheoChevalier** [comment]
I managed to trigger this error while testing, but unfortunately I don’t seem to be able to find STR…

> instance=http://localhost:3000 method=get path=/fr/ query={} statusCode=200 responseTime=46ms responsePayload="" tags=response timestring=2017-02-22T16:26:40.604Z
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ThankYou`. See https://fb.me/react-warning-keys for more information.
    in source (created by ThankYou)
    in ThankYou (created by RouterContext)
    in IntlProvider (created by createElement)
    in Provider (created by createElement)
    in createElement (created by RouterContext)
    in RouterContext
instance=http://localhost:3000 method=get path=/fr/jan-thank-you-superhero query={} statusCode=200 responseTime=19ms responsePayload="" tags=response timestring=2017-02-22T16:27:32.954Z

**Comment by ScottDowne** [comment]
@TheoChevalier I think that's unrelated to my patch.

If you go to https://donate.mozilla.org/en-US/jan-thank-you-superhero right now, and open the console, there should be a warning.

**Comment by ScottDowne** [comment]
@TheoChevalier I know this isn't a huge priority on your radar, but for what it's worth I fixed some merge conflicts.

**Comment by cadecairos** [comment]
When I run `npm test` locally, I see:

```

C:\Users\cade\code\donate.mozilla.org\src\mixins\stripe.js
  60:5  error  "reactGA" is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! donate.mozilla.org@0.0.1 test:lint: `eslint --ext .js,.jsx .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the donate.mozilla.org@0.0.1 test:lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cade\AppData\Roaming\npm-cache\_logs\2017-08-23T18_40_21_427Z-debug.log
ERROR: test:lint: None-Zero Exit(1);
npm ERR! Test failed.  See above for more details.
```

**Pull request merged**
