### PR TITLE
Make share url configurable

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

**Comment by ScottDowne** [comment]
I'm not convinced, either we always point to prod, and it always "works"

Or we link to application uri and it's busted locally.

**Comment by alicoding** [comment]
@ScottDowne I would rather have this busted locally than not able to test on Facebook debugger or share popup.

**Comment by ScottDowne** [comment]
@alicoding I didn't try this, but wouldn't this be resolved now that prod exists?

**Comment by jbuck** [comment]
@ScottDowne I think it should be configurable so we can test share changes locally and on staging, rather than testing on production. r+

**Comment by ScottDowne** [comment]
@jbuck I would agree with you, but that's not what this is doing.

Try to share locally now, nothing happens. facebook !== local

**Comment by ScottDowne** [comment]
Which might be fine.

**Comment by jbuck** [comment]
With ngrok it would!

**Pull request merged**
