### PR TITLE
[IT] - Translated 6 missing strings in italian localization

### PR DESCRIPTION
**Pull request by gialloporpora**

### CODE REVIEW

**Comment by alicoding** [comment]
@gialloporpora can you rebase once again?

**Comment by gialloporpora** [comment]
Sincerely I don't know, I am not very smart with git.
I'll try.

> @gialloporpora can you rebase once again?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/donate.mozilla.org/pull/575#issuecomment-149331434


-- 
Al Di Meola – Mediterranean Sundance 
<http://www.last.fm/music/Al+Di+Meola/_/Mediterranean+Sundance>
Two things are infinite: the universe and human stupidity; and I'm not 
sure about the universe.

**Comment by gialloporpora** [comment]
I have made a new pull request using my personal account:
https://github.com/mozilla/donate.mozilla.org/pull/596

I hope it works.
Sorry for the issue.

**Comment by alicoding** [comment]
Thanks for your PR :dancer:

**Pull request closed without merging**
