### PR TITLE
create test for this really helps us arrow and image

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
Test url is http://localhost:3000/en-US/?test=this-really-helps

@alicoding r?

**Comment by alicoding** [comment]
You didn't hash bunch of other images. Is that intentional?

**Comment by alicoding** [comment]
This looks good, but only for en-US right now?

**Comment by ScottDowne** [comment]
Yeah, only for en-US, the rest had UI issues but we only needed en-US to test.

I wanted a smaller patch.

**Comment by ScottDowne** [comment]
@alicoding and yes, I didn't bother to hash the images we were not using.

**Comment by alicoding** [comment]
@ScottDowne I would say just hash them, so when we have to use them in the future we can just grab and go :)

**Comment by ScottDowne** [comment]
@alicoding nah, file it. I'll do it later.

**Comment by alicoding** [comment]
r+ then

**Comment by ScottDowne** [comment]
Lol, thanks :)

**Pull request merged**
