### PR TITLE
enable test for stripe with reduced fields

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
To test this, add this to the query "?billingAddress=partial"

**Comment by ScottDowne** [comment]
@alicoding r?

**Comment by alicoding** [comment]
Code looks good. I'll test once I get to the office

**Comment by ScottDowne** [comment]
I think I'm going to add a handful of tests before it we land it.

**Comment by alicoding** [comment]
r+

**Pull request merged**
