### PR TITLE
stripe creds moved to sample.env

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
R?

To test run `cp sample.env .env`
Run `npm start`
In another window run `npm run test:selenium`

**Comment by alicoding** [comment]
```
$ npm run test:selenium

> donate.mozilla.org@0.0.1 test:selenium /Users/ali/projects/donate.mozilla.org
> node tests/selenium/server.js

/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Could not locate Firefox on the current system
    at Error (native)
    at /Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/firefox/binary.js:98:11
    at promise.ControlFlow.runInFrame_ (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at new Driver (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/firefox/index.js:277:36)
    at Builder.build (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/builder.js:460:14)
    at Object.<anonymous> (/Users/ali/projects/donate.mozilla.org/tests/selenium/server.js:7:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
From: Task: WebDriver.manage().timeouts().implicitlyWait(30000)
    at webdriver.WebDriver.schedule (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
    at webdriver.WebDriver.Timeouts.implicitlyWait (/Users/ali/projects/donate.mozilla.org/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1352:23)
    at Object.<anonymous> (/Users/ali/projects/donate.mozilla.org/tests/selenium/server.js:9:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "test:selenium"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! donate.mozilla.org@0.0.1 test:selenium: `node tests/selenium/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the donate.mozilla.org@0.0.1 test:selenium script 'node tests/selenium/server.js'.
npm ERR! This is most likely a problem with the donate.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tests/selenium/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls donate.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ali/projects/donate.mozilla.org/npm-debug.log

```

I feel like this is not really ideal to run a test you have to run two commands and they are in a separate window, but for now this is okay, but we need to optimize this process.

**Comment by alicoding** [comment]
I think its because I don't have Firefox installed on my system, but can we instead specify which Firefox version this can be run? or maybe Chrome for Chrome's user?

**Comment by ScottDowne** [comment]
Chrome can be set to run, but you need to npm install a chrome module for it. We can worry about that later.

Try installing Firefox if you can, and let me know if that fixes it.

**Comment by alicoding** [comment]
r+

**Comment by alicoding** [comment]
Can you please document regarding Firefox only for running the test or add support for other browser since this is not ideal at all to just run on Firefox only.

**Pull request merged**
