### PR TITLE
allow server to start and stop via nodejs and add a test that does th…

### PR DESCRIPTION
**Pull request by ScottDowne**
…is so travis can catch obvious server startup errors

### CODE REVIEW

**Comment by ScottDowne** [comment]
To test this, require in nonsense, like `require('nonsense');` in server.js.

Push that up to travis, and it should fail.

**Comment by ScottDowne** [comment]
r?

**Comment by alicoding** [comment]
do you still need to run two commands to run the test here?

**Comment by ScottDowne** [comment]
no, the selenium test now runs itself, but that's it.

What I did fix is selenium runs the server, and travis runs the server.

I didn't do selenium tests run via travis, and selenium stopping itself.

**Comment by alicoding** [comment]
r+

**Pull request merged**
