### PR TITLE
Remove more strings

### PR DESCRIPTION
**Pull request by TheoChevalier**
@ScottDowne yeah, should be easier to read now :)

### CODE REVIEW

**Comment by TheoChevalier** [comment]
By the way, I think this is the last bit remaining before I can enable more locales :) Communication to localizers should go out tomorrow with the first request ready: Social posts.
Would be great if we could enable locales at the same time

**Comment by ScottDowne** [comment]
@TheoChevalier Thanks for this :) :rocket:

**Comment by TheoChevalier** [comment]
@ScottDowne I kept some legacy strings here https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/messages.properties#L93-L106 is it safe to remove them even though they are in js files? They don’t seem to appear anywhere

**Comment by ScottDowne** [comment]
I think we can remove those too, but not sure. I think a new patch for just those, and I can review it tomorrow morning, if that would work for you?

Sorry, I saw your comment on legacy strings in the first patch, but you didn't have it here, so I didn't look again for legacy strings.

**Comment by TheoChevalier** [comment]
No worries, opening a new one ;)

**Pull request merged**
